import argparse
import re
from functools import partial
from pathlib import Path

import torch
from torch.utils.data import DataLoader

from bev_vlm.data import (
    FlatBEVQADataset,
    build_model_input_text,
    describe_anchor_brief,
    collate_flat_bev_qa,
    load_records,
    save_json,
    save_jsonl,
    task_type_to_id,
)
from bev_vlm.local_stage2 import LocalBEVQAStage2Model
from bev_vlm.tokenizer import SimpleCharTokenizer


def parse_args():
    parser = argparse.ArgumentParser(
        description="Run inference with the local Stage 2 BEV-VLM prototype and export predictions."
    )
    parser.add_argument("data", help="flat json/jsonl generated by tools/create_bev_vlm_data.py")
    parser.add_argument(
        "--checkpoint-dir",
        required=True,
        help="directory containing stage2_local_best.pt, stage2_config.json, and tokenizer.json",
    )
    parser.add_argument(
        "--checkpoint-name",
        default="stage2_local_best.pt",
        help="checkpoint file to load from the checkpoint directory",
    )
    parser.add_argument(
        "--output",
        default="outputs/bev_vlm/stage2_predictions.jsonl",
        help="prediction jsonl path",
    )
    parser.add_argument("--batch-size", type=int, default=4)
    parser.add_argument("--num-workers", type=int, default=0)
    parser.add_argument("--max-samples", type=int, default=None)
    parser.add_argument("--max-new-tokens", type=int, default=160)
    parser.add_argument(
        "--structured-fallback-tasks",
        nargs="*",
        default=["trust", "miss_summary"],
        help="task types that should use metadata-driven structured decoding in the local prototype",
    )
    parser.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")
    return parser.parse_args()


def clean_generated_text(text):
    text = str(text).strip()
    if not text:
        return text

    sentence_pattern = re.compile(r"[^。！？!?]*[。！？!?]?")
    pieces = [piece for piece in sentence_pattern.findall(text) if piece]
    deduped = []
    for piece in pieces:
        if deduped and piece == deduped[-1]:
            continue
        deduped.append(piece)
    text = "".join(deduped).strip()

    for delimiter in ["。", "！", "？"]:
        if delimiter in text:
            segments = [segment for segment in text.split(delimiter) if segment]
            compacted = []
            for segment in segments:
                if compacted and segment == compacted[-1]:
                    continue
                compacted.append(segment)
            text = delimiter.join(compacted)
            if text and not text.endswith(delimiter):
                text += delimiter
    return text.strip()


def safe_float(value):
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def render_miss_summary_from_metadata(record):
    metadata = record.get("metadata", {}) or {}
    missed_gt_objects = metadata.get("missed_gt_objects") or []
    missed_briefs = [describe_anchor_brief(anchor) for anchor in missed_gt_objects]
    missed_briefs = [brief for brief in missed_briefs if brief]
    if not missed_briefs:
        return "当前帧中没有发现明确的 GT 漏检目标，主要风险更可能来自低置信预测或场景本身较为空。"
    if len(missed_briefs) == 1:
        return f"当前帧共发现 1 个明确漏检目标，为 {missed_briefs[0]}。"
    return (
        f"当前帧共发现 {len(missed_briefs)} 个明确漏检目标，分别为 "
        + "、".join(missed_briefs)
        + "。"
    )


def render_trust_from_metadata(record):
    metadata = record.get("metadata", {}) or {}
    scene_uncertainty = safe_float(metadata.get("scene_uncertainty"))
    local_stats = metadata.get("primary_anchor_local_stats") or metadata.get("anchor_local_stats") or {}
    response_strengths = local_stats.get("response_strengths") or {}

    camera_strength = safe_float(response_strengths.get("camera")) or 0.0
    lidar_strength = safe_float(response_strengths.get("lidar")) or 0.0
    fused_strength = safe_float(response_strengths.get("fused")) or 0.0

    if camera_strength + lidar_strength > 1e-6:
        agreement = 1.0 - abs(camera_strength - lidar_strength) / (
            camera_strength + lidar_strength
        )
    else:
        agreement = 0.2
    fused_ratio = fused_strength / max(max(camera_strength, lidar_strength), 1e-6)
    fused_quality = max(0.0, min(1.0, fused_ratio / 1.2))
    uncertainty_term = 1.0 - scene_uncertainty if scene_uncertainty is not None else 0.25

    confidence = 0.50 * uncertainty_term + 0.25 * agreement + 0.25 * fused_quality
    if metadata.get("primary_anchor_type") == "missed_gt":
        confidence -= 0.08
    confidence = max(0.0, min(1.0, confidence))

    if confidence >= 0.7:
        advice = "建议维持当前行驶策略，但继续监测周边动态目标。"
    elif confidence >= 0.45:
        advice = "建议保守通过，并持续关注漏检目标附近区域。"
    else:
        advice = "建议减速并准备让行，因为当前感知证据不足以支持激进操作。"

    if scene_uncertainty is not None:
        return (
            f"当前场景整体感知可信度约为 {confidence:.2f}，"
            f"EDL 场景不确定性约为 {scene_uncertainty:.2f}。"
            f"{advice}"
        )
    return f"当前场景整体感知可信度约为 {confidence:.2f}。{advice}"


def render_structured_fallback(record):
    task_type = record.get("task_type")
    if task_type == "miss_summary":
        return render_miss_summary_from_metadata(record)
    if task_type == "trust":
        return render_trust_from_metadata(record)
    return None


def main():
    args = parse_args()
    checkpoint_dir = Path(args.checkpoint_dir).resolve()
    tokenizer = SimpleCharTokenizer.load(checkpoint_dir / "tokenizer.json")
    config = load_records(checkpoint_dir / "stage2_config.json")
    structured_fallback_tasks = set(args.structured_fallback_tasks or [])

    records = load_records(args.data)
    if args.max_samples is not None:
        records = records[: args.max_samples]
    if not records:
        raise ValueError("No flat QA samples were found for inference.")

    dataset = FlatBEVQADataset(
        records,
        tokenizer=tokenizer,
        max_question_length=int(config.get("max_question_length", 256)),
        max_answer_length=int(config.get("max_answer_length", 256)),
    )
    collate_fn = partial(collate_flat_bev_qa, pad_id=tokenizer.pad_id)
    data_loader = DataLoader(
        dataset,
        batch_size=args.batch_size,
        shuffle=False,
        num_workers=args.num_workers,
        collate_fn=collate_fn,
    )

    model = LocalBEVQAStage2Model(
        vocab_size=tokenizer.vocab_size,
        pad_id=tokenizer.pad_id,
        hidden_size=int(config["hidden_size"]),
        num_tasks=max(task_type_to_id(record["task_type"]) for record in records) + 1,
        connector_token_grid=tuple(config["token_grid"]),
    ).to(args.device)
    state_dict = torch.load(checkpoint_dir / args.checkpoint_name, map_location=args.device)
    model.load_state_dict(state_dict)
    model.eval()

    rows = []
    with torch.no_grad():
        for batch in data_loader:
            question_ids = batch["question_ids"].to(args.device)
            task_ids = batch["task_ids"].to(args.device)
            bev_tensors = {key: value.to(args.device) for key, value in batch["bev_tensors"].items()}
            generated = model.generate(
                question_ids=question_ids,
                task_ids=task_ids,
                bev_tensors=bev_tensors,
                bos_id=tokenizer.bos_id,
                eos_id=tokenizer.eos_id,
                max_new_tokens=args.max_new_tokens,
            )
            for sample_id, record, token_ids in zip(batch["ids"], batch["records"], generated):
                raw_prediction = tokenizer.decode(token_ids.tolist()).strip()
                prediction = clean_generated_text(raw_prediction)
                prediction_source = "model"
                if record.get("task_type") in structured_fallback_tasks:
                    structured_prediction = render_structured_fallback(record)
                    if structured_prediction:
                        prediction = structured_prediction
                        prediction_source = "structured_fallback"
                rows.append(
                    {
                        "id": sample_id,
                        "sample_token": record["sample_token"],
                        "task_type": record["task_type"],
                        "question": record["question"],
                        "model_input_text": build_model_input_text(record),
                        "reference": record["answer"],
                        "raw_prediction": raw_prediction,
                        "prediction": prediction,
                        "prediction_source": prediction_source,
                    }
                )

    output_path = Path(args.output).resolve()
    save_jsonl(output_path, rows)

    summary = {
        "data": str(Path(args.data).resolve()),
        "checkpoint_dir": str(checkpoint_dir),
        "checkpoint_name": args.checkpoint_name,
        "num_rows": len(rows),
        "num_nonempty_predictions": sum(bool(row["prediction"]) for row in rows),
    }
    save_json(output_path.with_suffix(".summary.json"), summary)
    print(f"Saved {len(rows)} predictions to {output_path}")


if __name__ == "__main__":
    main()
