import argparse
import json
import random
from functools import partial
from pathlib import Path

import numpy as np
import torch
from torch.optim import AdamW
from torch.utils.data import DataLoader

from bev_vlm.connectors import count_trainable_parameters
from bev_vlm.data import (
    FlatBEVQADataset,
    collate_flat_bev_qa,
    load_records,
    save_json,
    split_records,
)
from bev_vlm.local_stage2 import LocalBEVQAStage2Model
from bev_vlm.tokenizer import SimpleCharTokenizer


def parse_args():
    parser = argparse.ArgumentParser(
        description="Train the local Stage 2 BEV-VLM model with an MLP connector and a lightweight GRU text decoder."
    )
    parser.add_argument("data", help="flat json/jsonl generated by tools/create_bev_vlm_data.py")
    parser.add_argument(
        "--output-dir",
        default="outputs/bev_vlm/stage2_local",
        help="directory used to store checkpoints and tokenizer files",
    )
    parser.add_argument("--epochs", type=int, default=5)
    parser.add_argument("--batch-size", type=int, default=2)
    parser.add_argument("--learning-rate", type=float, default=3e-4)
    parser.add_argument("--weight-decay", type=float, default=1e-4)
    parser.add_argument("--hidden-size", type=int, default=256)
    parser.add_argument("--token-grid", nargs=2, type=int, default=[4, 4])
    parser.add_argument("--val-ratio", type=float, default=0.1)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--num-workers", type=int, default=0)
    parser.add_argument("--max-samples", type=int, default=None)
    parser.add_argument("--max-question-length", type=int, default=256)
    parser.add_argument("--max-answer-length", type=int, default=256)
    parser.add_argument("--smoke-steps", type=int, default=None)
    parser.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")
    return parser.parse_args()


def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


@torch.no_grad()
def evaluate(model, data_loader, device):
    model.eval()
    total_loss = 0.0
    steps = 0
    sample_prediction = None
    for batch in data_loader:
        batch = {
            "question_ids": batch["question_ids"].to(device),
            "answer_ids": batch["answer_ids"].to(device),
            "task_ids": batch["task_ids"].to(device),
            "bev_tensors": {key: value.to(device) for key, value in batch["bev_tensors"].items()},
            "records": batch["records"],
        }
        outputs = model(
            question_ids=batch["question_ids"],
            answer_ids=batch["answer_ids"],
            task_ids=batch["task_ids"],
            bev_tensors=batch["bev_tensors"],
        )
        total_loss += float(outputs["loss"].item())
        steps += 1
        if sample_prediction is None:
            sample_prediction = outputs["logits"][0].argmax(dim=-1).cpu().tolist()
    return total_loss / max(steps, 1), sample_prediction


def main():
    args = parse_args()
    set_seed(args.seed)

    records = load_records(args.data)
    if args.max_samples is not None:
        records = records[: args.max_samples]
    if not records:
        raise ValueError("No flat QA samples were found.")

    tokenizer = SimpleCharTokenizer()
    tokenizer.fit(
        [record["question"] for record in records] + [record["answer"] for record in records]
    )

    train_records, val_records = split_records(records, val_ratio=args.val_ratio, seed=args.seed)
    train_dataset = FlatBEVQADataset(
        train_records,
        tokenizer=tokenizer,
        max_question_length=args.max_question_length,
        max_answer_length=args.max_answer_length,
    )
    val_dataset = FlatBEVQADataset(
        val_records if val_records else train_records[:1],
        tokenizer=tokenizer,
        max_question_length=args.max_question_length,
        max_answer_length=args.max_answer_length,
    )

    collate_fn = partial(collate_flat_bev_qa, pad_id=tokenizer.pad_id)
    train_loader = DataLoader(
        train_dataset,
        batch_size=args.batch_size,
        shuffle=True,
        num_workers=args.num_workers,
        collate_fn=collate_fn,
    )
    val_loader = DataLoader(
        val_dataset,
        batch_size=args.batch_size,
        shuffle=False,
        num_workers=args.num_workers,
        collate_fn=collate_fn,
    )

    model = LocalBEVQAStage2Model(
        vocab_size=tokenizer.vocab_size,
        pad_id=tokenizer.pad_id,
        hidden_size=args.hidden_size,
        connector_token_grid=tuple(args.token_grid),
    ).to(args.device)
    optimizer = AdamW(
        model.parameters(),
        lr=args.learning_rate,
        weight_decay=args.weight_decay,
    )

    output_dir = Path(args.output_dir).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    tokenizer.save(output_dir / "tokenizer.json")

    history = []
    best_val_loss = float("inf")
    for epoch in range(1, args.epochs + 1):
        model.train()
        running_loss = 0.0
        steps = 0
        for step_idx, batch in enumerate(train_loader):
            if args.smoke_steps is not None and step_idx >= args.smoke_steps:
                break
            batch = {
                "question_ids": batch["question_ids"].to(args.device),
                "answer_ids": batch["answer_ids"].to(args.device),
                "task_ids": batch["task_ids"].to(args.device),
                "bev_tensors": {
                    key: value.to(args.device) for key, value in batch["bev_tensors"].items()
                },
            }
            outputs = model(
                question_ids=batch["question_ids"],
                answer_ids=batch["answer_ids"],
                task_ids=batch["task_ids"],
                bev_tensors=batch["bev_tensors"],
            )
            loss = outputs["loss"]
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            running_loss += float(loss.item())
            steps += 1

        train_loss = running_loss / max(steps, 1)
        val_loss, _ = evaluate(model, val_loader, args.device)
        history.append(
            {
                "epoch": epoch,
                "train_loss": train_loss,
                "val_loss": val_loss,
            }
        )
        if val_loss <= best_val_loss:
            best_val_loss = val_loss
            torch.save(model.state_dict(), output_dir / "stage2_local_best.pt")
            torch.save(model.connector.state_dict(), output_dir / "connector.pt")
        print(
            f"epoch={epoch} train_loss={train_loss:.4f} "
            f"val_loss={val_loss:.4f} "
            f"connector_params={count_trainable_parameters(model.connector)}"
        )

    save_json(output_dir / "history.json", history)
    save_json(
        output_dir / "stage2_config.json",
        {
            "data": str(Path(args.data).resolve()),
            "epochs": args.epochs,
            "batch_size": args.batch_size,
            "learning_rate": args.learning_rate,
            "hidden_size": args.hidden_size,
            "token_grid": args.token_grid,
            "vocab_size": tokenizer.vocab_size,
            "connector_trainable_params": count_trainable_parameters(model.connector),
        },
    )
    torch.save(model.state_dict(), output_dir / "stage2_local_last.pt")
    print(f"Saved Stage 2 local artifacts to {output_dir}")


if __name__ == "__main__":
    main()
